name: ramp-air-passengers
channels:
  - defaults
dependencies:
  - pip
  - numpy
  - scikit-learn>=0.22
  - joblib
  - cloudpickle
  - pandas
  - matplotlib
  - jupyter
  - shap
  - pip:
    - ramp-workflow
    - holidays
    - geopy
